### ISSUE TITLE
Document is not defined -> SSR

### ISSUE THREAD

**Issue by ICTVTS3** [svelte-plugins/datepicker#11]
I'm experiencing a bug where a lot of the times on refresh my localhost crashes with the error 'document is not defined'. It stems from this line in the datepicker.svelte component:

  $: theme !== null && document.documentElement.setAttribute('data-picker-theme', theme);
  
 Thanks for checking it out :)

**Comment by hilkeheremans** [comment]
hi @dysfunc - just revisiting this since I am also seeing this issue.

I see your fix in `/src` of v1.0.4 but it appears the `/dist` does not have the most recently compiled code in the published npm package. You sure v1.0.4 was actually _built_ before it was published?

**Comment by dysfunc** [comment]
Well, it looks like you both were right. I apologize for the delay on this fix. I just published 1.0.5. Can you please install the latest and let me know if your problem is resolved

**Comment by ICTVTS3** [comment]
It's still causing the issues. You can solve it by adding

`import { browser } from '$app/env';`

And changing the line in question to 

`  $: browser && theme !== null && document && document.documentElement.setAttribute('data-picker-theme', theme);`

**Comment by dysfunc** [comment]
This has been fixed and a new version has been release `1.0.6`. Please install the latest and let me know if this issue has been resolved for you.
