### ISSUE TITLE
🐛 Keyboard entry of time causes calendar to go to December 1969.

### ISSUE THREAD

**Issue by cmjoseph07** [svelte-plugins/datepicker#13]
**Describe the bug**
When using the time picker feature, if you use the keyboard to manually type values it breaks the calendar and jumps to 1969.

**To Reproduce**

1. Go to example REPL in docs
2. Add the time picker feature
3. Manually type a time, ex: (03:30 PM)
4. Calendar jumps even on example REPL

**Expected behavior**
To just enter time and for the calendar to not jump dates.

**Screenshots**
<img width="318" alt="Screenshot 2024-03-05 at 7 45 37 AM" src="https://github.com/svelte-plugins/datepicker/assets/95969273/76785349-4719-4c28-9b8d-de27347fae0d">

**Comment by dysfunc** [comment]
This has been fixed and a new version has been release `1.0.6`. Please install the latest let me know if this issue has been resolved for you.

**Comment by dysfunc** [comment]
Can you pull down the changes and let me know if this fixes everything for you https://github.com/svelte-plugins/datepicker/pull/16

**Comment by cmjoseph07** [comment]
@dysfunc 

Sorry for the delayed response, it does look like everything is working good now. Thank you for the fix!

**Comment by cmjoseph07** [comment]
@dysfunc 

Sorry to bother you on this but I have been testing for awhile and I can't get the active button for the date selection to be any other color than blue. Can you advise which variable I should be overriding?

**Comment by dysfunc** [comment]
```
--datepicker-calendar-range-selected-background: green;`
```
