### ISSUE TITLE
Using themes

### ISSUE THREAD

**Issue by smurfb** [svelte-plugins/datepicker#14]
Hello!

I cant get themes to work as they should.  I change the theme-attribute in  datepicker, but it doesnt use the new tags. I guess im doing it wrong. Would it be possible to add an example how to use themes? 

Thanks for your work!

Regards
Joel

**Comment by dysfunc** [comment]
The readme has the same example:

https://svelte.dev/repl/d6e9a6b3a0664671b6d068bbe857272f?version=4.2.12
