### ISSUE TITLE
Calendar html buttons without 'type' property🐛 

### ISSUE THREAD

**Issue by fabiofanta** [svelte-plugins/datepicker#17]
**Describe the bug**
Html buttons on calendar are without type="button". So they get type="submit" as default and it could trigger form submission

**Comment by dysfunc** [comment]
Thanks for submitting an issue @fabiofanta. I included this change inside the open PR addressing some other issues
https://github.com/svelte-plugins/datepicker/pull/16/commits/73a023b9a6b7b798978fb9542de73a91632e4797
