### ISSUE TITLE
🐛 Cannot set multi-year range

### ISSUE THREAD

**Issue by gabrielstellini** [svelte-plugins/datepicker#18]
**Describe the bug**
Hi!
I am trying to set a maximum allowed date in the range picker (a week into the future).
There doesn't seem to be a min/max prop I could use, but I found `enabledDates` . This doesn't seem to allow multi-year ranges - is this a bug?
The `disabledDates` also seemed like a good option, but I couldn't find a way to only set the start date (and let it go on forever).

Is there another way to achieve this?

**To Reproduce**

1. Go to https://stackblitz.com/edit/vitejs-vite-mfpcpk?file=src%2FApp.svelte
2. View the example dates

**Expected behavior**

 - Have a maximum/minimum date as prop or
 - Allow multi-year enabled dates

**Screenshots**

![image](https://github.com/svelte-plugins/datepicker/assets/16836689/6d273797-c804-4837-82cb-e21083680173)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version "^1.0.6"

**Additional context**

**Comment by dysfunc** [comment]
I updated your stackblitz https://stackblitz.com/edit/vitejs-vite-qwdtrc?file=src%2FApp.svelte

**Comment by gabrielstellini** [comment]
Thank you!
