### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by hemants1703** [svelte-plugins/datepicker#21]
#### Description
The current documentation is incomplete in certain areas, making it difficult for users to understand or utilize the project effectively.

#### Problem Statement
For Preset Ranges, the code that is mentioned in the documentation is incomplete which caused me debugging time of hours on a simple single code insertion

#### Impact
The simple incompleteness is causing issues for developer to properly implement the Date Range Picker in their projects.

#### Proposed Solution
Fix the documentation

#### Screenshot of the incomplete documentation
<img width="758" alt="Svelte-Date-Picker-Doc-Issue" src="https://github.com/svelte-plugins/datepicker/assets/58618028/687e0688-522b-4da4-b4e3-bb8e63e7c973">

**Comment by dysfunc** [comment]
#24 fixes addresses this
